[[test.genesis]]
address = "KyberSwapPooL111111111111111111111111111111"
program = "programs/kyberswap_pool_solana.so"

[[test.genesis]]
address = "KyberSwapFactory111111111111111111111111111"
program = "programs/kyberswap_factory_solana.so"

[[test.genesis]]
address = "KyberSwapRouter1111111111111111111111111111"
program = "programs/kyberswap_router_solana.so"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/*.ts"