[[test.genesis]]
address = "ZuluSwapPooL111111111111111111111111111111"
program = "programs/zuluswap_pool_solana.so"

[[test.genesis]]
address = "ZuluSwapFactory111111111111111111111111111"
program = "programs/zuluswap_factory_solana.so"

[[test.genesis]]
address = "ZuluSwapRouter1111111111111111111111111111"
program = "programs/zuluswap_router_solana.so"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/*.ts"